platform :ios, '9.0'
use_frameworks!

target 'InnerpeaceSDK-Example' do

    pod 'lottie-ios', '~> 2.1'
    pod 'SnapKit', '~> 4.0'
    pod 'SVProgressHUD'
    pod 'InnerpeaceSDK', :path => '../'
    pod 'Files', '~> 2.0.0'
    pod 'NaptimeFileProtocol', :git => "git@github.com:EnterTech/Naptime-FileProtocol-iOS.git", :branch => "develop"
    pod 'Zip', :git => 'https://github.com/cobi-bike/Zip.git', :branch => 'fix-minizip-reference'

end
